name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # atau ganti sesuai nama branch utama kamu

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project
        run: |
          npm install
          npm run build  # pastikan script ini menghasilkan folder `dist`

      - name: Deploy `dist` folder to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
